title:        Basics
url:          http://basics.apievangelist.com/
raw_url: https://api-evangelist-data.github.io/names/apis/

tag: Names
logo:         https://kinlane-productions2.s3.amazonaws.com/api-evangelist/api-evangelist-logo-400.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

github_user: api-evangelist
github_repo: basics
github_branch: master

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://kinlane-productions2.s3.amazonaws.com/footer/empowered-by-you-banner.png
footer_image_width: 60

collections:
  lifecycle:
    output: true
    permalink: /lifecycle/:path/
  definitions:
    output: true
    permalink: /definitions/:path/
  governance:
    output: true
    permalink: /governance/:path/
